### PR TITLE
Pre-release cleanup

### PR DESCRIPTION
**Pull request by szhorvat**
This PR cleans up the package a little bit for the 1.0 release.

 - Header guards in public headers use non-conflicting non-reserved names.
 - Fixes some missing headers (for `plfit_moments`)
 - Restricts symbol visibility in shared libs
 - `Release` build type by default

Tested a shared lib build with igraph, it works.

Did not test SWIG.

Do we really need `plfit.map`, given that it's GNU-specific? If yes, do versions need to be changed in that file?

I won't submit any more polish changes than these.

### CODE REVIEW

**Comment by ntamas** [comment]
The `.map` file was added by @jgmbenoit and my understanding is that it helps with Debian packaging. See ba161a1e. I think we need to re-generate the file before release, just in case, but I see no reason to remove it.

**Comment by ntamas** [comment]
I'll go through the rest thoroughly later, but it's probably going to be okay. I might move public headers into a separate `include` folder just to make things explicit.

**Comment by szhorvat** [comment]
> I think we need to re-generate the file before release, just in case, but I see no reason to remove it.

I checked, using the command at the top of that file, there's no change to the list of functions.

**Comment by ntamas** [comment]
Thanks! I'll probably take care of the include files in a separate commit (if I decide to do so).

**Pull request merged**
