### PR TITLE
chore: update vendored liblbfgs from https://github.com/chokkan/liblbfgs

### PR DESCRIPTION
**Pull request by szhorvat**
This attempts to update liblbfgs, and causes a crash in the test suite. Let's check if the crash is due to an issue that is present independently of the liblbfgs update. Funny thing is, it doesn't happen when compiling in Debug mode.

This is what I see on my machine:

```
$ test/test_hzeta
dyld[29868]: main executable has no entry point
fish: Job 1, 'test/test_hzeta' terminated by signal SIGABRT (Abort)
```

Occurs _only_ with `test_hzeta`.

### CODE REVIEW

**Comment by szhorvat** [comment]
This is because tests use internal functions.

**Comment by szhorvat** [comment]
Why are the tests not failing here when using a shared library build? Some tests use non-public functions that don't get exported from the shard lib.

**Comment by szhorvat** [comment]
> Windows tests _are_ failing

This is because the DLL is not in the PATH. My attempted fix fails because the generator expression `$<TARGET_FILE_DIR:plfit>` is not getting evaluated. I don't know why, I give up.



> I see there's some hackery in the `TEST_CASES_INTERNAL` section.

The `main executable has no entry point` error might relate to this, but again I'm stuck and I give up.

**Comment by szhorvat** [comment]
The main executable has no entry point error occurs only with `-O2` or `-O3`, and only with Apple Clang. It doesn't happen with GCC or LLVM Clang. Maybe let's just ignore this.

**Comment by szhorvat** [comment]
I think we should merge this as-is:

 - It updates liblbfgs
 - Cleans up test headers
 - Expands CI runs to shared builds
 - Makes sure that shared build tests pass on Windows

Quite a heterogeneous set of changes, I know.

**Comment by ntamas** [comment]
Thanks!

**Pull request merged**
