### PR TITLE
allow #comment-eol (and fix parse error machinery)

### PR DESCRIPTION
**Pull request by jgmbenoit**
Attempt to allow commented line or end-of-line in input data files.
Along the way the parsing errors machinery was fixed.

### CODE REVIEW

**Comment by ntamas** [comment]
Seems good, thanks!

Can I ask you to add a test file in `data/` containing some comments that the parser should skip, and update `data/README.rst` to mention this file? Also, we should probably mention it somewhere in `README.rst` at the root as well that comments are now allowed in the input file.

**Comment by jgmbenoit** [comment]
On my way to add comments and examples. Please note that data is currently ignored by .gitignore .

**Comment by ntamas** [comment]
`data/` is now un-ignored in 78eaa36

**Comment by jgmbenoit** [comment]
Please let me know if something is wrong or can be improved.

**Comment by ntamas** [comment]
Ah, sorry, this has slipped through the cracks. Merging it right now.

**Pull request merged**
