### PR TITLE
import and incorporate the lnhzeta family functions

### PR DESCRIPTION
**Pull request by jgmbenoit**
in view to fix the underflow issue #13 . The underflow issue is fixed. Note that the function plfit_i_ks_test_discrete must be certainly revisited.

### CODE REVIEW

**Comment by ntamas** [comment]
Thanks a lot! I'll check the `plfit_i_ks_test_discrete` part.

**Comment by ntamas** [comment]
The math seems to check out for me in the new version of `plfit_i_ks_test_discrete`; I will probably add a comment about all the magic going on there, but otherwise it seems to be okay.

**Comment by ntamas** [comment]
Comment added in 7472718.

**Comment by jgmbenoit** [comment]
Thanks for the merge. Concerning plfit_i_ks_test_discrete, I do not like the difference of logarithms and the differences around: a lot of cancellations may occurs here (eg, (1+epsilon_machine/10)-1 = 0). To workaround it, I see two solutions: (a) figure out a `magic formula' without cancellations; (b) implement an efficient different function (that takes into account the cancellations).

**Comment by ntamas** [comment]
That’s correct, however the current version is still a significant improvement over the previous one so I’ll keep what we have and then start thinking about alternative solutions on the side.

**Pull request merged**
